//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMoonHUB.Application.Services.Configuration.FluentValidations {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FluentValidantionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidantionsMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelMoonHUB.Application.Services.Configuration.FluentValidations.FluentValidanti" +
                            "onsMessages", typeof(FluentValidantionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must introduce a CheckIn date.
        /// </summary>
        public static string EmpyCheckIn {
            get {
                return ResourceManager.GetString("EmpyCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must introduce a CheckOut date.
        /// </summary>
        public static string EmpyCheckOut {
            get {
                return ResourceManager.GetString("EmpyCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel Id can&apos;t be empy.
        /// </summary>
        public static string EmpyHotelId {
            get {
                return ResourceManager.GetString("EmpyHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must introduce a number of guests.
        /// </summary>
        public static string EmpyNumberOfGuests {
            get {
                return ResourceManager.GetString("EmpyNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel Id can&apos;t be less of 0.
        /// </summary>
        public static string HotelIdUnder0 {
            get {
                return ResourceManager.GetString("HotelIdUnder0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must introduce a currency.
        /// </summary>
        public static string NullCurrency {
            get {
                return ResourceManager.GetString("NullCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must introduce a number of rooms.
        /// </summary>
        public static string NullNumberOfRooms {
            get {
                return ResourceManager.GetString("NullNumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t be negative guests.
        /// </summary>
        public static string NumberOfGuestsUnder0 {
            get {
                return ResourceManager.GetString("NumberOfGuestsUnder0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must book at least one room.
        /// </summary>
        public static string NumberOfRoomsUnder0 {
            get {
                return ResourceManager.GetString("NumberOfRoomsUnder0", resourceCulture);
            }
        }
    }
}
